- name: ADT Download
  hosts: all
  tasks:
    - name: Download the folder from Artifactory
      get_url:
        url: "{{ ARTIFACTORY_HOSTNAME }}/artifactory/ui/artifactactions/downloadfolder?repoKey={{ artifactory_folder_path.split('/')[0] }}&path={{ artifactory_folder_path.split('/')[1:] | join('/') | regex_replace('\\/$', '') }}&archiveType={{ ARTIFACTORY_ARCHIVE_TYPE }}&includeChecksumFiles=false"
        validate_certs: "{{ ARTIFACTORY_VALIDATE_CERTIFICATES }}"
        dest: "{{ ARTIFACTORY_DOWNLOAD_DIRECTORY }}"
        headers:
           X-JFrog-Art-Api: "{{ ARTIFACTORY_API_TOKEN }}"
    - name: Message from the {{ tower_inventory_name }} environment
      debug:
        msg: "Deploying application {{ artifactory_folder_path.split('/')[0] }} and {{ artifactory_folder_path.split('/')[1:] | join('/') | regex_replace('\\/$', '') }} and {{ ARTIFACTORY_VALIDATE_CERTIFICATES }} and {{ ARTIFACTORY_HTTP_PROXY }} "
