- name: ADT Download
  hosts: all
  tasks:
    - name: Download the folder from Artifactory
      get_url:
        url: "{{ ARTIFACTORY_HOSTNAME }}/api/archive/download/{{ artifactory_folder_path }}?archiveType={{ ARTIFACTORY_ARCHIVE_TYPE }}"
        dest: "{{ ARTIFACTORY_DOWNLOAD_DIRECTORY }}"
        headers:
           X-JFrog-Art-Api: "{{ ARTIFACTORY_API_TOKEN }}"
    - name: Message from the {{ tower_inventory_name }} environment
      debug:
        msg: "Deploying application "
