- name: Artifactory download
  hosts: all
  tasks:
    - name: Download from Artifactory
      get_url:
        url: "{{ ARTIFACTORY_HOSTNAME }}/artifactory/{{ item }}"
        dest: "{{ artifactory_download_directory }}/{{ item }}"
        headers:
           X-JFrog-Art-Api: "{{ ARTIFACTORY_API_TOKEN }}"
      with_items:
           - "{{ artifactory_repository_path.split(',') }}"
