- name: ADT Deployment
  hosts: all
  tasks:
    - name: Create directory for artifactory download
      file:
        path: "{{ ARTIFACTORY_DOWNLOAD_DIRECTORY }}/{{ item.rsplit('/', 1)[0] }}"
        state: directory
      with_items:
           - "{{ artifactory_folder_path.split(',') }}"
- name: ADT Deployment
  hosts: all
  tasks:
    - name: Download from Artifactory
      get_url:
        url: "{{ ARTIFACTORY_HOSTNAME }}/artifactory/{{ artifactory_folder_path }}?archiveType={{ ARTIFACTORY_ARCHIVE_TYPE }}"
        dest: "{{ ARTIFACTORY_DOWNLOAD_DIRECTORY }}"
        headers:
           X-JFrog-Art-Api: "{{ ARTIFACTORY_API_TOKEN }}"
    - name: Message from the {{ tower_inventory_name }} environment
      debug:
        msg: "Deploying application "
